# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/Gui/Connexion/connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.Model.User import User
# from src.Gui.Admin.AdminWindow import AdminWindow
from src.Gui.Masque.MainMasque import MasqueWindow
from src.PasswordManager.PasswordManager import PasswordManager
from src.Global import id_user
import sys


class Ui_Connexion(object):
    def setupUi(self, Connexion):
        self.masque_window = None
        self.me = Connexion
        
        Connexion.setObjectName("Connexion")
        Connexion.resize(521, 221)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Connexion)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_authentification = QtWidgets.QLabel(Connexion)
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(22)
        self.label_authentification.setFont(font)
        self.label_authentification.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_authentification.setObjectName("label_authentification")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_authentification)
        self.label_matricule = QtWidgets.QLabel(Connexion)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.label_matricule.setFont(font)
        self.label_matricule.setObjectName("label_matricule")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_matricule)
        self.input_matricule = QtWidgets.QLineEdit(Connexion)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.input_matricule.setFont(font)
        self.input_matricule.setObjectName("input_matricule")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_matricule)
        self.label_password = QtWidgets.QLabel(Connexion)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.input_password = QtWidgets.QLineEdit(Connexion)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.input_password.setFont(font)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_password)
        self.btn_connexion = QtWidgets.QPushButton(Connexion)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(20)
        self.btn_connexion.setFont(font)
        self.btn_connexion.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.btn_connexion.setObjectName("btn_connexion")
        self.btn_connexion.clicked.connect(self.authentification)#clique bouton pour s'authentifier
        self.input_password.returnPressed.connect(self.okPressed)#taper sur la touche entrée
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_connexion)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(Connexion)
        QtCore.QMetaObject.connectSlotsByName(Connexion)

    def retranslateUi(self, Connexion):
        _translate = QtCore.QCoreApplication.translate
        Connexion.setWindowTitle(_translate("Connexion", "Connexion"))
        self.label_authentification.setText(_translate("Connexion", "Authentification"))
        self.label_matricule.setText(_translate("Connexion", "Matricule: "))
        self.label_password.setText(_translate("Connexion", "Mot de passe:"))
        self.btn_connexion.setText(_translate("Connexion", "Connexion"))

    def authentification(self):
        matricule = self.input_matricule.text()
        plain_password = self.input_password.text()
        user = None

        if User.select().where(User.matricule == matricule).exists():
            user = User.select().where(User.matricule == matricule).get()
            hashed_password = user.password
            # print(hashed_password)
            # sys.exit()
            if PasswordManager.checkPassword(user_plain_password=plain_password,user_hash_password=hashed_password):
                if user.roles.type == "admin":
                    self.me.close() #fermeture de la fenetre de connexion
                    # id_user = user.id
                    self.masque_window = MasqueWindow(user.id)
                    self.masque_window.show()
            else:
                self.invalidCredentials()

        else: #indentification erreur
            #affiche le message d'erreur,puis on vide les champs matricule, et password
            # QtWidgets.QMessageBox.critical(None, "Error", "Invalid Credentials")
            # self.input_matricule.setText("")
            # self.input_password.setText("")
            # #remettre le focus sur le champ matricule
            # self.input_matricule.setFocusPolicy(QtCore.Qt.StrongFocus)
            # self.input_matricule.setFocus()
            # return
            self.invalidCredentials()


    def okPressed(self):
        self.authentification()

    def invalidCredentials(self):
        QtWidgets.QMessageBox.critical(None, "Error", "Invalid Credentials")
        self.input_matricule.setText("")
        self.input_password.setText("")
        #remettre le focus sur le champ matricule
        self.input_matricule.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_matricule.setFocus()
        return



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Connexion = QtWidgets.QWidget()
#     ui = Ui_Connexion()
#     ui.setupUi(Connexion)
#     Connexion.show()
#     sys.exit(app.exec_())
